### ISSUE TITLE
[question] How to use custom UID / GID with grafana docker image

### ISSUE THREAD

**Issue by RaymondMouthaan** [fg2it/grafana-on-raspberry#37]
Hello @fg2it,

Currently, I have my own docker image available on docker hub, which is based upon yours. It adds some configurations to run the image under a custom uid and gid. 

However looking at the official v5.1.0, this custom uid and gid should now be supported and my own docker image wouldn't be needed anymore. 

I've tried your lastest version like this:

```
version: "3.6"

services:
  grafana:
    image: fg2it/grafana-armhf:v5.1.0
    ports:
      - "3000:3000"
    volumes:
#      - /mnt/swarm-volumes/grafana/data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
#    user: "1000"
    environment:
      - GF_UID=1000
      - GF_GID=1000
    deploy:
      replicas: 1
```

Within the container:
```
root@c3cb3da395dd:/# id grafana
uid=472(grafana) gid=472(grafana) groups=472(grafana)

root@c3cb3da395dd:/# ls -al /var/lib/grafana/
total 404
drwxrwxrwx 1 grafana grafana   4096 Apr 29 11:33 .
drwxr-xr-x 1 root    root      4096 Apr 28 22:26 ..
-rw-r--r-- 1 grafana grafana 393216 Apr 29 11:33 grafana.db
drwxrwxrwx 2 grafana grafana   4096 Apr 28 22:26 plugins

root@c3cb3da395dd:/# echo $GF_UID $GF_GID
1000 1000
```

So from the info above you can see that GF_UID and GF_GID didn't change the uid and gid for user grafana.

I also tried this according to [grafana docker install](http://docs.grafana.org/installation/docker/):
```
version: "3.6"

services:
  grafana:
    image: fg2it/grafana-armhf:v5.1.0
    ports:
      - "3000:3000"
    volumes:
#      - /mnt/swarm-volumes/grafana/data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    user: "1000"
#    environment:
#     - GF_UID=1000
#      - GF_GID=1000
    deploy:
      replicas: 1
```

Within the container:
```
root@83b148de388f:/# id grafana
uid=472(grafana) gid=472(grafana) groups=472(grafana)

root@83b148de388f:/# ls -al /var/lib/grafana/
total 404
drwxrwxrwx 1 grafana grafana   4096 Apr 29 11:40 .
drwxr-xr-x 1 root    root      4096 Apr 28 22:26 ..
-rw-r--r-- 1    1000 root    393216 Apr 29 11:40 grafana.db
drwxrwxrwx 2 grafana grafana   4096 Apr 28 22:26 plugins
```

So from the info above you can see that user: 1000 didn't change the uid and gid for user grafana, but it did set user 1000 on the grafana.db. The plugins directory however remains assigned to grafana user and group.

I was expecting in one of the above try-outs that all files and dirs within /var/lib/grafana would belong to grafana:grafana, where the uid and gid both could be customly  set, so that persistence would be possible with an "external" user. 

While writing this, I just realise that it probably is an issue upon the official grafana ...

Can you help me out on this one or do I need to submit an issue at official grafana project?

Thanks in advance.
Raymond
